# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: movin123
      POSTGRES_DB: travelgodb
    network_mode: host