version: '3.9'

services:
  db:
    image: 'postgres'
    network_mode: "host"
    ports:
      - "5432:5432"    
    restart: always
    environment:
      POSTGRES_PASSWORD: 'movin123'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'travelgodb'